export const SET_BURGER_BUN = 'SET_BURGER_BUN'
export const SET_BURGER_INGREDIENTS = 'SET_BURGER_INGREDIENTS'
export const CLEAR_BURGER = 'CLEAR_BURGER'
export const SET_INGREDIENTS_FOR_BURGER = 'SET_INGREDIENTS_FOR_BURGER'