export const SET_OPEN_MODAL = 'SET_OPEN_MODAL'
export const SET_CLOSE_MODAL = 'SET_CLOSE_MODAL'
export const SET_TARGET_MODAL = 'SET_TARGET_MODAL'
export const CLEAR_TARGET_MODAL = 'CLEAR_TARGET_MODAL'